In [1]:
%load_ext autoreload
%autoreload 2

import os, sys

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [5]:
import pandas as pd
from datetime import datetime

In [10]:
df = pd.read_csv("../data/transactions.csv", index_col="transaction_id", parse_dates=["transaction_date"])
df.head()

,transaction_date,transaction_type,category,amount_ngn,payment_channel,description,suspicious_flag
transaction_id,,,,,,,
TXN0001,2026-04-13,Expense,Utilities,24563.25,POS,Utilities transaction,0
TXN0002,2026-09-28,Expense,Bank Charges,11339.64,Direct Debit,Bank Charges transaction,0
TXN0003,2026-04-17,Income,Sales,16232.84,Bank Transfer,Sales transaction,0
TXN0004,2026-03-13,Expense,Utilities,3152.87,Direct Debit,Utilities transaction,0
TXN0005,2026-07-08,Income,Sales,18004.45,Cash,Sales transaction,1

In [11]:
df.head()

,transaction_date,transaction_type,category,amount_ngn,payment_channel,description,suspicious_flag
transaction_id,,,,,,,
TXN0001,2026-04-13,Expense,Utilities,24563.25,POS,Utilities transaction,0
TXN0002,2026-09-28,Expense,Bank Charges,11339.64,Direct Debit,Bank Charges transaction,0
TXN0003,2026-04-17,Income,Sales,16232.84,Bank Transfer,Sales transaction,0
TXN0004,2026-03-13,Expense,Utilities,3152.87,Direct Debit,Utilities transaction,0
TXN0005,2026-07-08,Income,Sales,18004.45,Cash,Sales transaction,1

In [7]:
start = datetime(2026, 4, 1)
stop = datetime(2026, 9, 1)

In [25]:
related_df = df[(df['transaction_date'] >= start) & (df['transaction_date'] <= stop) & (df['transaction_type'] == "Income")]
related_df

,transaction_date,transaction_type,category,amount_ngn,payment_channel,description,suspicious_flag
transaction_id,,,,,,,
TXN0003,2026-04-17,Income,Sales,16232.84,Bank Transfer,Sales transaction,0
TXN0005,2026-07-08,Income,Sales,18004.45,Cash,Sales transaction,1
TXN0013,2026-05-11,Income,Sales,31460.53,Bank Transfer,Sales transaction,0
TXN0014,2026-05-30,Income,Sales,59226.77,Cash,Sales transaction,0
TXN0026,2026-07-09,Income,Sales,16384.04,Cash,Sales transaction,0
...,...,...,...,...,...,...,...
TXN0370,2026-05-27,Income,Sales,10409.93,Bank Transfer,Sales transaction,0
TXN0386,2026-06-17,Income,Service Revenue,3971.46,POS,Service Revenue transaction,0
TXN0390,2026-04-05,Income,Sales,50993.18,Cash,Sales transaction,0
TXN0392,2026-08-30,Income,Service Revenue,21669.17,Bank Transfer,Service Revenue transaction,0
TXN0400,2026-04-15,Income,Sales,4458.28,POS,Sales transaction,1

In [36]:
cats = related_df.groupby('category')['amount_ngn'].sum()
cats.head(5)

category
Customer Payment     832463.84
Other Income          92110.49
Sales               1947486.19
Service Revenue      276018.62
Name: amount_ngn, dtype: float64